name: Dispatch
run-name: >-
  Build [macos=${{ inputs.build-macos }} ubuntu=${{ inputs.build-ubuntu }}
  win-x64=${{ inputs.build-windows-x64 }} win-arm64=${{ inputs.build-windows-arm64 }}]
  package=${{ inputs.package }} 🏗️
on:
  workflow_dispatch:
    inputs:
      build-macos:
        description: Build for macOS Universal
        type: boolean
        default: true
      build-ubuntu:
        description: Build for Ubuntu x86_64
        type: boolean
        default: true
      build-windows-x64:
        description: Build for Windows x64
        type: boolean
        default: true
      build-windows-arm64:
        description: Build for Windows ARM64
        type: boolean
        default: true
      package:
        description: Create installer / package
        required: false
        type: choice
        default: 'auto'
        options:
          - 'auto'
          - 'true'
          - 'false'
permissions:
  contents: write
jobs:
  build:
    uses: ./.github/workflows/build-project.yaml
    with:
      build-macos: ${{ inputs.build-macos }}
      build-ubuntu: ${{ inputs.build-ubuntu }}
      build-windows-x64: ${{ inputs.build-windows-x64 }}
      build-windows-arm64: ${{ inputs.build-windows-arm64 }}
      package: ${{ inputs.package }}
    secrets: inherit
